# Generated by Django 2.2.28 on 2022-07-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_container', '0003_restaurant_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='first_date',
            field=models.DateTimeField(default="2021-01-05 06:00:00.000000-09:00"),
            preserve_default=False,
        ),
    ]
